### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by krishaamer** [VeliovGroup/Meteor-iron-router-meta#12]
Hey, thanks for the package! Does it work with the latest Meteor deployed on Galaxy? I've followed the instructions however can't get anything to show up in the meta.

Thanks,
Kris

**Comment by dr-dimitru** [comment]
Should work, we use this package daily, but never tested on Galaxy.
Could you post your code here?

**Comment by dr-dimitru** [comment]
@krishaamer ?

**Comment by dr-dimitru** [comment]
Closed due to no response from topic starter
